### ISSUE TITLE
Пункт меню для покупки GALT в эмиссии

### ISSUE THREAD

**Issue by Jonybang** [andromedaspace/WIJG#102]

**Comment by Jonybang** [comment]
Реализован интерфейс для выполнения покупки у эмиссии и необходимая логика в Universe классе, но эмиссия не работает как нужно, claimAll вызывает ошибку
```
(node:35339) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: false == true
    at ERC20.transfer (/Users/jonybang/workspace/WIJG/contracts/ERC20.ts:39:9)
    at Emission.claim (/Users/jonybang/workspace/WIJG/contracts/Emission.ts:155:20)
    at Emission.claimAll (/Users/jonybang/workspace/WIJG/contracts/Emission.ts:172:18)
    at DAO.Universe.claimEmissionTokens (/Users/jonybang/workspace/WIJG/common/Universe.ts:662:23)
    at /Users/jonybang/workspace/WIJG/cli/stage-1.ts:291:26
(node:35339) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35339) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Jonybang** [comment]
Исправлено
