### ISSUE TITLE
Отсутствие сообщения при повторной ставке на новый аукцион земли

### ISSUE THREAD

**Issue by Jonybang** [andromedaspace/WIJG#215]
Когда пользователь после первого аукциона пытается подать на второй аукцион запрос - не выходит сообщение с таймером аукциона

**Comment by Jonybang** [comment]
Ошибка

(node:7869) UnhandledPromiseRejectionWarning: Error: ETELEGRAM: 400 Bad Request: message to delete not found
    at request.then.resp (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegram.js:280:15)
From previous event:
    at Request.RP$exposed [as then] (/Users/jonybang/workspace/WIJG/node_modules/request-promise-core/lib/plumbing.js:145:61)
    at TelegramBot._request (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegram.js:268:8)
    at TelegramBot.deleteMessage (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegram.js:1625:17)
    at Object.<anonymous> (/Users/jonybang/workspace/WIJG/tg/app.ts:185:31)
    at step (/Users/jonybang/workspace/WIJG/tg/app.ts:32:23)
    at Object.next (/Users/jonybang/workspace/WIJG/tg/app.ts:13:53)
    at /Users/jonybang/workspace/WIJG/tg/app.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/jonybang/workspace/WIJG/tg/app.ts:3:12)
    at /Users/jonybang/workspace/WIJG/tg/app.ts:183:14
    at TelegramBot.<anonymous> (/Users/jonybang/workspace/WIJG/tg/app.ts:223:15)
    at TelegramBot.emit (/Users/jonybang/workspace/WIJG/node_modules/eventemitter3/index.js:182:35)
    at TelegramBot.processUpdate (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegram.js:594:12)
    at updates.forEach.update (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegramPolling.js:110:22)
    at Array.forEach (<anonymous>)
    at _lastRequest._getUpdates.then.updates (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegramPolling.js:106:17)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at TelegramBotPolling._polling (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegramPolling.js:103:8)
    at Timeout._pollingTimeout.setTimeout [as _onTimeout] (/Users/jonybang/workspace/WIJG/node_modules/node-telegram-bot-api/src/telegramPolling.js:168:56)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:7869) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7869) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
